# Joint trajectory controller
position_trajectory_controller:
    #type: effort_controllers/JointTrajectoryController
    type: "position_controllers/JointTrajectoryController"
    joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6
    #gains:
        #joint_1: {p: 10000.0, i: 500.0, d: 200.0, i_clamp: 100.0}
        #joint_2: {p: 10000.0, i: 500.0, d: 200.0, i_clamp: 100.0}
        #joint_3: {p: 10000.0, i: 500.0, d: 100.0, i_clamp: 100.0}
        #joint_4: {p: 100.0, i: 0.0, d: 10.0, i_clamp: 0.0}
        #joint_5: {p: 100.0, i: 0.0, d: 10.0, i_clamp: 0.0}
        #joint_6: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0.0}
    #constraints:
        #goal_time: 0.6
        #stopped_velocity_tolerance: 0.5
        #joint_1: {trajectory: 0.1, goal: 0.1}
        #joint_2: {trajectory: 0.1, goal: 0.1}
        #joint_3: {trajectory: 0.1, goal: 0.1}
        #joint_4: {trajectory: 0.1, goal: 0.1}
        #joint_5: {trajectory: 0.1, goal: 0.1}
        #joint_6: {trajectory: 0.1, goal: 0.1}
    #stop_trajectory_duration: 0.5
    state_publish_rate: 50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20

