joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 2.72271363311
    has_acceleration_limits: false
    max_acceleration: 0
  joint_2:
    has_velocity_limits: true
    max_velocity: 2.72271363311
    has_acceleration_limits: false
    max_acceleration: 0
  joint_3:
    has_velocity_limits: true
    max_velocity: 2.72271363311
    has_acceleration_limits: false
    max_acceleration: 0
  joint_4:
    has_velocity_limits: true
    max_velocity: 5.75958653158
    has_acceleration_limits: false
    max_acceleration: 0
  joint_5:
    has_velocity_limits: true
    max_velocity: 5.75958653158
    has_acceleration_limits: false
    max_acceleration: 0
  joint_6:
    has_velocity_limits: true
    max_velocity: 10.7337748998
    has_acceleration_limits: false
    max_acceleration: 0